apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-kueue
namePrefix: pipelines-multikueue-plugin-

images:
- name: controller
  newName: quay.io/prbindal/pipelines-multikueue-controller
  newTag: "34"
resources:
- multikueue-controller.yaml
- rbac/service_account.yaml
- rbac/role.yaml
- rbac/role_binding.yaml
- rbac/kueue-role.yaml
